defaults: &defaults
  <% if ENV["REDIS_URL"] %>
  url: <%= ENV["REDIS_URL"] %>
  <% else %>
  host: redis
  <% end %>
  db: 0

development:
  <<: *defaults

test:
  <<: *defaults
  db: 1

production:
  <<: *defaults
