production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/artspace_books_production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8983
    log_level: INFO
    path: /solr/artspace_books

test:
  disabled: true
